version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: avbot
    container_name: avbot
    restart: unless-stopped
    env_file: .env

    volumes:
      - .:/home/node/app
    networks:
      - app-network
    command: npm start

networks:
  app-network:
    driver: bridge