version: '3'
name: AvBot

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: avbot
    container_name: avbot
    restart: unless-stopped
    env_file: .env

    volumes:
      - .:/home/node/app
    networks:
      - app-network
    command: npm start

networks:
  app-network:
    driver: bridge

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER }}
          registry: docker.pkg.github.com
          repository: drph4nt0m/avbot-v3/avbot
          tag_with_ref: true
